bearbeitet von Marcia Perez Heilig

@startuml
hide empty members
skin rose

class Trip {
    -id: number
    -dest_country: string
    -departure_date: string
    -return_date: string
    -cities: Array<City>
    -tourguide: string
    constructor(dest_country: string, departure_date: string, return_date: string, tourguide: string)

}

class City {
    -name: string
    -duration_of_stay: number
    constructor(name: string, duration_of_stay: number)
}

Trip "1" --> "1..n" City
@enduml